[metadata]
  name = "gcp"
  author = "adin"

[global]
  plan = "dht"
  case = "barrier"
  total_instances = 1000
  builder = "docker:go"
  runner = "cluster:k8s"
  [global.build_config]
    push_registry = true
    registry_type = "aws"

[[groups]]
  id = "cypress"
  [groups.instances]
    count = 0
    percentage = 1.0
  [groups.build]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-dht:b1fd5d8d433e"
    [groups.run.test_params]
      bucket_size = "4"
      client_mode = "false"
      f_undialable = "0.5"
      n_find_peers = "50"
      n_providing = "1"
      record_count = "5"
      timeout_secs = "600"
