[metadata]
  name = "find-provs"
  author = "adin"

[global]
  plan = "dht"
  case = "find-providers"
  total_instances = 200
  builder = "docker:go"
  runner = "local:docker"

[[groups]]
  id = "balsa"
  [groups.instances]
    count = 0
    percentage = 1.0
  [groups.build]
  [groups.run]
    artifact = "bc8109352b50"
    [groups.run.test_params]
      bucket_size = "4"
      client_mode = "false"
      f_undialable = "0.9"
      n_providing = "1"
      record_count = "5"
      timeout_secs = "2000"

[[groups]]
  id = "cypress"
  [groups.instances]
    count = 0
    percentage = 0.0
  [groups.build]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "v0.4.2-0.20200204202258-35d3e4a5d43e"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-autonat"
      version = "v0.1.2-0.20200204200147-902af8cb7b6a"
  [groups.run]
    artifact = "65c32a8821e4"
    [groups.run.test_params]
      bucket_size = "4"
      client_mode = "false"
      f_undialable = "0.9"
      n_providing = "1"
      record_count = "5"
      timeout_secs = "2000"