[metadata]
  name = "find-provs"
  author = "adin"

[global]
  plan = "dht"
  case = "find-providers"
  total_instances = 400
  builder = "docker:go"
  runner = "cluster:k8s"
  [global.build_config]
    push_registry = true
    registry_type = "aws"

[[groups]]
  id = "balsam"
  [groups.instances]
    count = 0
    percentage = 1.0
  [groups.build]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-dht:07736f7b34c3"
    [groups.run.test_params]
      bucket_size = "4"
      client_mode = "false"
      f_undialable = "0.9"
      n_providing = "1"
      record_count = "5"
      timeout_secs = "2000"